/*******************************************************************************
 Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
 Licensed under the MIT or Apache License; see LICENSE in the source repository
 root for authoritative license information.﻿

 **NOTE** This code was generated by a tool and will occasionally be
 overwritten. We welcome comments and issues regarding this code; they will be
 addressed in the generation tool. If you wish to submit pull requests, please
 do so for the templates in that tool.

 This code was generated by Vipr (https://github.com/microsoft/vipr) using
 the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).
 ******************************************************************************/
package com.microsoft.sampleservice.fetchers;

import com.microsoft.sampleservice.*;
import com.google.common.util.concurrent.*;
import com.microsoft.services.orc.core.*;
import com.microsoft.services.orc.core.Readable;

/**
 * The type  ItemBFetcher.
 */
public class ItemBFetcher extends OrcEntityFetcher<ItemB,ItemBOperations> 
                                     implements Readable<ItemB> {

     /**
     * Instantiates a new ItemBFetcher.
     *
     * @param urlComponent the url component
     * @param parent the parent
     */
     public ItemBFetcher(String urlComponent, OrcExecutable parent) {
        super(urlComponent, parent, ItemB.class, ItemBOperations.class);
    }

     /**
     * Add parameter.
     *
     * @param name the name
     * @param value the value
     * @return the fetcher
     */
    public ItemBFetcher addParameter(String name, Object value) {
        addCustomParameter(name, value);
        return this;
    }

     /**
     * Add header.
     *
     * @param name the name
     * @param value the value
     * @return the fetcher
     */
    public ItemBFetcher addHeader(String name, String value) {
        addCustomHeader(name, value);
        return this;
    }

        
}
