/**
 * ****************************************************************************
 * Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
 * Licensed under the MIT or Apache License; see LICENSE in the source repository
 * root for authoritative license information.﻿
 * <p/>
 * *NOTE** This code was generated by a tool and will occasionally be
 * overwritten. We welcome comments and issues regarding this code; they will be
 * addressed in the generation tool. If you wish to submit pull requests, please
 * do so for the templates in that tool.
 * <p/>
 * This code was generated by Vipr (https://github.com/microsoft/vipr) using
 * the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).
 * ****************************************************************************
 */
package com.microsoft.sampleservice.fetchers;

import com.microsoft.sampleservice.*;
import com.google.common.util.concurrent.*;
import com.microsoft.services.orc.core.*;
import com.microsoft.services.orc.http.*;
import com.microsoft.services.orc.serialization.*;

import java.util.Map;
import java.util.Set;

import static com.microsoft.services.orc.core.Helpers.*;


/**
 * The type SampleEntityCollectionOperations
 */
public class SampleEntityCollectionOperations extends EntityCollectionOperations {

    /**
     * Instantiates a new SampleEntityCollectionOperations.
     *
     * @param urlComponent the url component
     * @param parent       the parent
     */
    public SampleEntityCollectionOperations(String urlComponent, OrcExecutable parent) {
        super(urlComponent, parent);
    }

    /**
     * Add parameter.
     *
     * @param name  the name
     * @param value the value
     * @return the collection operations
     */
    public SampleEntityCollectionOperations addParameter(String name, Object value) {
        addCustomParameter(name, value);
        return this;
    }

    /**
     * Add header.
     *
     * @param name  the name
     * @param value the value
     * @return the collection operations
     */
    public SampleEntityCollectionOperations addHeader(String name, String value) {
        addCustomHeader(name, value);
        return this;
    }


    /**
     * SomeFunction listenable future.
     *
     * @param path the path
     * @return the listenable future
     */
    public ListenableFuture<SampleComplexType> someFunction(String path) {

        java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
        map.put("path", path);

        Request request = getResolver().createRequest();
        request.setVerb(HttpVerb.GET);

        String functionComponent = appendFunctionComponent("Microsoft.SampleService.SomeFunction", map);
        request.getUrl().appendPathComponent(functionComponent);

        ListenableFuture<OrcResponse> future = oDataExecute(request);

        return transformToEntityListenableFuture(transformToStringListenableFuture(future), SampleComplexType.class, getResolver());


    }

    private String appendFunctionComponent(String functionName, Map<String, Object> arguments) {

        String result;
        if (!arguments.isEmpty()) {
            result = "('";
            for (Map.Entry<String, Object> entrySet : arguments.entrySet()) {
                result = result + String.format("%s,%s", entrySet.getKey(), entrySet.getValue());
            }
            result = result + "')";
        } else {
            result = "()";
        }
        return functionName + result;
    }


}
