/*******************************************************************************
 Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
 Licensed under the MIT or Apache License; see LICENSE in the source repository
 root for authoritative license information.﻿

 **NOTE** This code was generated by a tool and will occasionally be
 overwritten. We welcome comments and issues regarding this code; they will be
 addressed in the generation tool. If you wish to submit pull requests, please
 do so for the templates in that tool.

 This code was generated by Vipr (https://github.com/microsoft/vipr) using
 the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).
 ******************************************************************************/
package com.microsoft.sampleservice;



/**
 * The type Item.
*/
public class Item extends Entity {

    public Item(){
        setODataType("#Microsoft.SampleService.Item");
    }
            
    private String ItemName;
     
    /**
    * Gets the Item Name.
    *
    * @return the String
    */
    public String getItemName() {
        return this.ItemName; 
    }

    /**
    * Sets the Item Name.
    *
    * @param value the String
    */
    public void setItemName(String value) { 
        this.ItemName = value; 
        valueChanged("ItemName", value);

    }
}

