
/**
 * ****************************************************************************
 * Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
 * Licensed under the MIT or Apache License; see LICENSE in the source repository
 * root for authoritative license information.﻿
 * <p/>
 * *NOTE** This code was generated by a tool and will occasionally be
 * overwritten. We welcome comments and issues regarding this code; they will be
 * addressed in the generation tool. If you wish to submit pull requests, please
 * do so for the templates in that tool.
 * <p/>
 * This code was generated by Vipr (https://github.com/microsoft/vipr) using
 * the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).
 * ****************************************************************************
 */
package com.microsoft.services.orc.core;

import java.util.concurrent.ConcurrentHashMap;

/**
 * The type ODataBaseEntity.
 */
public class ODataBaseEntity {

    protected String $$__ODataType;

    ConcurrentHashMap<String, Object> $$$__$$$updatedValues = new ConcurrentHashMap<String, Object>();

    protected void setODataType(String value) {
        this.$$__ODataType = value;
    }

    public ConcurrentHashMap<String, Object> getUpdatedValues() {

        return new ConcurrentHashMap<String, Object>($$$__$$$updatedValues);
    }

    public void valueChanged(String property, Object payload) {
        $$$__$$$updatedValues.put(property, payload);
    }
}
